server:
    port: 8080

spring:
    profiles:
        active: dev
    data:
#        mongodb:
#            host: localhost
#            port: 27017
#            database: gestionedeleghe
        mongodb:
            host: ds061721.mongolab.com
            port: 61721
            database: CloudFoundry_40i1vhtc_mn6t5hcp
            username: admin
            password: admin

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: gestionedeleghe


